version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: pascal90/zigbee2mqtt-multi-coordinator-addon:latest
    volumes:
      - ./options.json:/data/options.json
      - ./zigbee2mqtt-multi-coordinator:/config/zigbee2mqtt-multi-coordinator
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Amsterdam